server:
  port: 80
spring:
  thymeleaf:
    cache: false
  # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://106.13.232.5:3306/study-security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver

mengxuegu:
  security:
    authentication:
      loginPage: /login/page  # 响应认证(登录)页面URL
      loginProcessingUrl: /login/form   # 登录表单提交处理Url
      usernameParameter: name  # 登录表单用户名的属性名
      passwordParameter: pwd # 登录表单密码的属性名
      staticPaths: # 静态资源 "/dist/**", "/modules/**", "/plugins/**"
      - /dist/**
      - /modules/**
      - /plugins/**
      loginType: REDIRECT # 认证之后 响应的类型：JSON/REDIRECT
      imageCodeUrl: /code/image #获取图形验证码
      mobileCodeUrl: /mobile/page #发送手机验证码地址
      mobilePageUrl: /code/mobile #前往手机登录界面
      tokenValiditySeconds: 604800
